### ISSUE TITLE
Not working with Swift 4

### ISSUE THREAD

**Issue by haroldogtf** [Chakery/AyLoading#3]
The project is not working with Swift 4

This error apper in `iOS+IndicatorView.swift
`
<img width="922" alt="screen shot 2018-05-06 at 22 44 04" src="https://user-images.githubusercontent.com/1682169/39681228-2eb0d824-517f-11e8-9885-3fa62f5ea50c.png">

**Comment by chakery** [comment]
just now migrated to swift4.x, use 3.0.0 version please.

```
pod 'AyLoading', '3.0.0'
```
